export const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
export const FILTER_BY_LOCATION = "FILTER_BY_LOCATION";
export const ORDER_BY_RATING = "ORDER_BY_RATING";
export const ORDER_BY_NAME = "ORDER_BY_NAME";