const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
const GET_FILTERED = "GET_FILTERED";
const GET_AMOUNTPAGES = "GET_AMOUNTPAGES"
const ERROR = "ERROR"
const GET_RESTOURANT_ID = "GET_RESTOURANT_ID"
const GET_ADMIN_USER = "GET_ADMIN_USER"
const POST_USER = "POST_USER"
const GET_USER_EMAIL = "GET_USER_EMAIL"
const LOGIN = "LOGIN"
const LOADING = "LOADING"

module.exports = {
    GET_ALL_RESTORANTS,
    GET_FILTERED,
    GET_AMOUNTPAGES,
    ERROR,
    GET_RESTOURANT_ID,
    GET_ADMIN_USER,
    POST_USER,
    GET_USER_EMAIL,
    LOGIN,
    LOADING

}