const GET_ALL_RESTORANTS = "GET_ALL_RESTORANTS";
const GET_FILTERED = "GET_FILTERED";
const CREATED_RESTORANTS = "CREATED_RESTORANTS"


module.exports = {
    GET_ALL_RESTORANTS,
    GET_FILTERED,
    CREATED_RESTORANTS
}